import path from 'node:path';
import type { ComponentInfo } from '../models/index.js';
import { withoutPlatformSuffix } from '../utils/index.js';
import { missingArgs } from './csf-story.js';
import { findPlatformVariants } from './platform-variants.js';
import type { StoryArg } from './story-args.js';
import { deriveArgs } from './story-args.js';
import { quote } from './story-file.js';

/** Attributes past this width read better one per line. */
const EXAMPLE_LINE_BUDGET = 90;

export interface ScaffoldFile {
  /** Repository-relative, POSIX separated path. */
  filePath: string;
  contents: string;
}

export interface ScaffoldFolder {
  /** Folder name inside the scaffold directory, unique across the plan. */
  name: string;
  /** Repository-relative path of the folder itself. */
  directory: string;
  /** The application file the folder re-exports from. */
  origin: string;
  /**
   * The component as it appears inside the folder, pointing at the local
   * re-export. Hand this to a story generator and the story lands beside the
   * re-export and imports it, rather than reaching back into the application.
   */
  entry: ComponentInfo;
  /** Everything except the story, which is the story generator's business. */
  files: ScaffoldFile[];
}

export type ScaffoldResult =
  | { status: 'planned'; folder: ScaffoldFolder }
  | { status: 'skipped'; component: string; filePath: string; reason: string };

export interface ScaffoldOptions {
  /** Repository-relative directory to place the component folders in. */
  directory: string;
}

/**
 * Plans a folder per component: a re-export of the component, a re-export of
 * its props type, an example, and a barrel.
 *
 * Nothing here copies application code. Every file points back at the original,
 * so the application is left exactly as it was and the two can never drift.
 */
export function planScaffold(
  components: readonly ComponentInfo[],
  options: ScaffoldOptions,
): ScaffoldResult[] {
  const platformVariants = findPlatformVariants(components);
  const reasonToSkip = (component: ComponentInfo): string | undefined =>
    skipReason(component, options) ?? platformVariants.get(component);

  const eligible = components.filter((component) => reasonToSkip(component) === undefined);
  const folderNames = assignFolderNames(eligible);

  return components.map((component) => {
    const skip = reasonToSkip(component);
    if (skip) {
      return {
        status: 'skipped',
        component: component.name,
        filePath: component.filePath,
        reason: skip,
      };
    }

    const name = folderNames.get(component) ?? component.name;
    return { status: 'planned', folder: buildFolder(component, name, options) };
  });
}

/**
 * The note that explains the directory to whoever finds it.
 *
 * These files are meant to be read and judged, not silently trusted, so the
 * folder says what it is, where each component really lives, and what adopting
 * it would involve.
 */
export function renderScaffoldReadme(folders: readonly ScaffoldFolder[]): string {
  const rows = folders.map((folder) => `| \`${folder.name}/\` | \`${folder.origin}\` |`);

  return [
    '# Components',
    '',
    'Generated by Repo2DS. Nothing in the application was changed to create it.',
    '',
    'Each folder re-exports a component from where it already lives, so there is still only',
    'one copy of every component. Deleting this directory changes nothing.',
    '',
    '| Folder | Component |',
    '| --- | --- |',
    ...rows,
    '',
    '## What is in a folder',
    '',
    '- `<Name>.tsx` re-exports the component.',
    '- `<Name>.types.ts` re-exports its props type, when the source file exports one.',
    '- `<Name>.stories.tsx` is a Storybook story built from the props Repo2DS found.',
    '- `<Name>.example.tsx` uses the component with those props.',
    '- `index.ts` re-exports both, so the folder can be imported as a unit.',
    '',
    '## Adopting it',
    '',
    'Move a component implementation into its folder, replace the re-export with the real',
    'code, and repoint the imports in the application. Do that one component at a time: until',
    'you do, this directory is additive and safe to throw away.',
    '',
  ].join('\n');
}

/**
 * Why a component gets no folder, or `undefined` when it gets one.
 *
 * A component that already lives in the scaffold directory has been adopted:
 * the folder now holds the real implementation, and generating a re-export over
 * it would have the file import itself.
 */
function skipReason(component: ComponentInfo, options: ScaffoldOptions): string | undefined {
  if (component.exportType === 'unknown') {
    return 'component is not exported, so it cannot be re-exported';
  }

  if (isInside(component.filePath, options.directory)) {
    return 'component already lives in the components directory';
  }

  return undefined;
}

function isInside(filePath: string, directory: string): boolean {
  const relative = path.posix.relative(directory, filePath);
  return relative.length > 0 && !relative.startsWith('..') && !path.posix.isAbsolute(relative);
}

function buildFolder(
  component: ComponentInfo,
  folderName: string,
  options: ScaffoldOptions,
): ScaffoldFolder {
  const directory = path.posix.join(options.directory, folderName);
  // The suffix is dropped so the bundler resolves the platform, exactly as the
  // application's own imports do.
  const source = relativeImport(directory, withoutPlatformSuffix(component.filePath));
  const entryPath = path.posix.join(directory, `${component.name}.tsx`);

  const files: ScaffoldFile[] = [
    { filePath: entryPath, contents: renderReExport(component, source) },
  ];

  const typesFile = renderTypesFile(component, source);
  if (typesFile) {
    files.push({
      filePath: path.posix.join(directory, `${component.name}.types.ts`),
      contents: typesFile,
    });
  }

  files.push({
    filePath: path.posix.join(directory, `${component.name}.example.tsx`),
    contents: renderExample(component),
  });

  files.push({
    filePath: path.posix.join(directory, 'index.ts'),
    contents: renderBarrel(component),
  });

  return {
    name: folderName,
    directory,
    origin: component.filePath,
    entry: { ...component, filePath: entryPath, exportType: 'named' },
    files,
  };
}

/** `export { Button } from '../../../src/components/Button';` */
function renderReExport(component: ComponentInfo, source: string): string {
  const specifier =
    component.exportType === 'default' ? `default as ${component.name}` : component.name;
  return `export { ${specifier} } from '${source}';\n`;
}

/**
 * Only a type the source file exports can be re-exported. When it is inline or
 * private the folder simply has no types file, which is honest: inventing an
 * interface from the extracted props would drop everything Repo2DS could not
 * resolve.
 */
function renderTypesFile(component: ComponentInfo, source: string): string | undefined {
  if (!component.propsType?.exported) {
    return undefined;
  }
  return `export type { ${component.propsType.name} } from '${source}';\n`;
}

function renderBarrel(component: ComponentInfo): string {
  const lines = [`export { ${component.name} } from './${component.name}';`];

  if (component.propsType?.exported) {
    lines.push(`export type { ${component.propsType.name} } from './${component.name}.types';`);
  }

  return `${lines.join('\n')}\n`;
}

/**
 * A compiling usage of the component, with the props it is usually given.
 *
 * A required prop whose value cannot be inferred — a list, a shape, a type from
 * another file — becomes a parameter of the example rather than an invented
 * value. The example still compiles, and what Repo2DS could not work out is
 * stated in the code instead of hidden.
 */
function renderExample(component: ComponentInfo): string {
  const args = deriveArgs(component.props);
  const attributes = args.map(renderAttribute);
  const missing = missingArgs(component.props, args);
  const takesProps = missing.length > 0 || !component.propsResolved;
  const parts = [...(takesProps ? ['{...props}'] : []), ...attributes];

  const inline = parts.length === 0 ? '' : ` ${parts.join(' ')}`;
  const opening = `    <${component.name}${inline} />`;

  const element =
    opening.length <= EXAMPLE_LINE_BUDGET
      ? [opening]
      : [`    <${component.name}`, ...parts.map((part) => `      ${part}`), '    />'];

  return [...exampleHeader(component, missing), '  return (', ...element, '  );', '}', ''].join(
    '\n',
  );
}

function exampleHeader(component: ComponentInfo, missing: readonly string[]): string[] {
  const componentProps = `ComponentProps<typeof ${component.name}>`;
  const importLines = [
    "import type { ComponentProps } from 'react';",
    '',
    `import { ${component.name} } from './${component.name}';`,
    '',
  ];

  if (!component.propsResolved) {
    return [
      ...importLines,
      '// Repo2DS could not read this props type, so the example takes the props as given.',
      `export function ${component.name}Example(props: ${componentProps}) {`,
    ];
  }

  if (missing.length === 0) {
    return [
      `import { ${component.name} } from './${component.name}';`,
      '',
      `export function ${component.name}Example() {`,
    ];
  }

  const propsType = `${component.name}ExampleProps`;

  return [
    ...importLines,
    '// Repo2DS could not infer a value for these props. Pass them in to render the example.',
    `type ${propsType} = Pick<`,
    `  ${componentProps},`,
    `  ${missing.map(quote).join(' | ')}`,
    '>;',
    '',
    `export function ${component.name}Example(props: ${propsType}) {`,
  ];
}

function renderAttribute(arg: StoryArg): string {
  if (arg.value.kind === 'expression') {
    return `${arg.name}={${arg.value.code}}`;
  }

  const value = arg.value.value;

  if (typeof value === 'boolean') {
    return value ? arg.name : `${arg.name}={false}`;
  }

  if (typeof value === 'number') {
    return `${arg.name}={${value}}`;
  }

  // A double quote would end the attribute and a line break would be folded
  // into a space, so anything but plain text falls back to an expression.
  return fitsInAttribute(value) ? `${arg.name}="${value}"` : `${arg.name}={${quote(value)}}`;
}

/** JSX attribute text is taken literally, apart from `"`, `{`, `}` and whitespace. */
function fitsInAttribute(value: string): boolean {
  // eslint-disable-next-line no-control-regex
  return !/["{}\\]|[\u0000-\u001f\u2028\u2029]/.test(value);
}

/**
 * One folder per component, named after the component. Two components can share
 * a name across directories, so the losers of a clash are qualified by the
 * directory they came from, and only then by a counter.
 */
function assignFolderNames(components: readonly ComponentInfo[]): Map<ComponentInfo, string> {
  const shared = new Set<string>();
  const seen = new Set<string>();
  for (const component of components) {
    if (seen.has(component.name)) {
      shared.add(component.name);
    }
    seen.add(component.name);
  }

  const taken = new Set<string>();
  const names = new Map<ComponentInfo, string>();

  for (const component of components) {
    const base = shared.has(component.name)
      ? `${component.name}-${directorySlug(component.filePath)}`
      : component.name;

    let name = base;
    for (let suffix = 2; taken.has(name); suffix += 1) {
      name = `${base}-${suffix}`;
    }

    taken.add(name);
    names.set(component, name);
  }

  return names;
}

/** `src/admin/Button.tsx` gives `admin`; a file at the root gives `root`. */
function directorySlug(filePath: string): string {
  const directory = path.posix.dirname(filePath);
  const segment = directory === '.' ? 'root' : path.posix.basename(directory);
  return (
    segment
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'root'
  );
}

function relativeImport(fromDirectory: string, toFile: string): string {
  const target = toFile.replace(/\.(tsx|ts|jsx|js)$/, '');
  const relative = path.posix.relative(fromDirectory, target);
  return relative.startsWith('.') ? relative : `./${relative}`;
}
